{
 "title": "BookStore dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Orders", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Orders Placed",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "expr": "sum(metrics_bookstore_total_orders_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Orders Placed by City",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "expr": "metrics_bookstore_total_orders_count",
     "legendFormat": "{{City}}"
    }
   ]
  },
  {
   "title": "Avg. Order Price",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "expr": "metrics_bookstore_orders_price_sum / metrics_bookstore_orders_price_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg. Number of Books per Order",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "expr": "metrics_bookstore_orders_number_of_books_sum / metrics_bookstore_orders_number_of_books_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of books per order",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "expr": "metrics_bookstore_orders_number_of_books_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Price Distribution per Order",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "expr": "metrics_bookstore_orders_price_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Books", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Total Number of Books Available in the Store",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "expr": "metrics_bookstore_books_total_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Books Added",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 5, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "expr": "metrics_bookstore_books_added_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Books Deleted",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 9, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "expr": "metrics_bookstore_books_deleted_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Books Updated",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 13, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "expr": "metrics_bookstore_books_updated_count",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Categories", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Categories Added",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "expr": "metrics_bookstore_categories_added_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Categories Updated",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "expr": "metrics_bookstore_categories_updated_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Categories Deleted",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "expr": "metrics_bookstore_categories_deleted_count",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}